autenticacion/urls.py
from django.urls import path



from autenticacion import views

app_name='autenticacion'

urlpatterns = [
    
    path('crearUsuario', views.crearUsuario, name='crearUsuario'),

    path('cuenta', views.cuentaUsuario, name='cuentaUsuario'),

    path('actualizarCliente', views.actualizarCliente, name='actualizarCliente'),

    path('loginUsuario', views.loginUsuario, name='loginUsuario'),
    
    path('logout', views.logoutUsuario, name='logoutUsuario'),

    # Asignamos la función 'cerrar_sesion' a la URL 'cerrar/', con el nombre 'cerrar_sesion'.
    #path('cerrar/', cerrar_sesion, name='cerrar_sesion'),

    

#    path('login/', LoginView.as_view(), name='login'),
]

pedidos/urls.py
from django.urls import path, include

from . import views

#de las vistas importamos las clases que creamos
#from .views import pedido_en_proceso

app_name='pedido'


urlpatterns = [
        
    
    path('registrarPedido', views.registrarPedido, name='registrarPedido'),
    
    path('pruebapaypal/', views.view_that_asks_for_money, name='pruebapaypal'),
   
    path('confirmarPedido/', views.confirmarPedido, name='confirmarPedido'),

    path('gracias/', views.gracias, name='gracias'),
    #path('pedido_procesado/', views.pedido_en_proceso.as_view(), name='pedido_procesado'),  # Cambia la ruta para el pedido procesado

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

# Importa la configuración global de tu proyecto Django
from django.conf import settings

# Importa la función 'static' para servir archivos estáticos como imágenes y hojas de estilo CSS, para que puedas ver cómo se ven en tu aplicación.
from django.conf.urls.static import static

# Define las URL de tu aplicación
urlpatterns = [
    path('admin/', admin.site.urls),
    #Dejo la raiz vacia para definir que ese sea su pag home

    path('', include('web.urls')),

    path('autenticacion/', include('autenticacion.urls')),
    
    path('pedidos/', include('pedidos.urls')),

    path('paypal/', include("paypal.standard.ipn.urls")),
]

# Si el modo DEBUG está activado (entorno de desarrollo), 
# agrega las URL para servir archivos multimedia (MEDIA_URL)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views


app_name='web'
# Define las URL de tu aplicación
urlpatterns = [
    #dejo la raiz vacia para definir que ese sera su pagina home
    path('', views.index, name='index'),
    path('ProductosPorCategoria/<int:categoria_id>', views.ProductosPorCategoria, name='ProductosPorCategoria'),
    path('BuscarProducto', views.BuscarProducto, name='BuscarProducto'),
    path('Producto/<int:producto_id>', views.ProductoDetalle, name='ProductoDetalle'),
    path('carrito', views.carrito, name='carrito'),
    path('agregarCarrito/<int:producto_id>', views.agregarCarrito, name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>', views.eliminarProductoCarrito, name='eliminarProductoCarrito'),
    path('limpiarCarrito', views.limpiarCarrito, name='limpiarCarrito'),
]

pedidos/models.py
# Importa el módulo models de Django
from django.db import models

# Importa el modelo User de django.contrib.auth.models
from django.contrib.auth.models import User

from autenticacion.models import Cliente
from web.models import Producto


"""CUANDO EL USUARIO HACE EL PEDIDO PASAMOS TODA LA INFORMACION DEL CARRITO GUARDADA EN LA SESION A LA BASE DE DATOS, ES LO QUE NORMALMENTE SE HACE CUANDO UN USUARIO PROCESA EL CARRITO"""

# Define el modelo Pedido, esta vista corresponde es al estado del pedido, cuando el cliente hace el pedido
class Pedido(models.Model):
    
    # Define una relación ForeignKey con el modelo Cliente para representar el cliente que realizó el pedido
    customer = models.ForeignKey(Cliente, on_delete=models.RESTRICT)

    # Define un campo DateTimeField para almacenar la fecha de registro del pedido (se establecerá automáticamente)
    registration_date = models.DateTimeField(auto_now_add=True)

    # Define un campo CharField para almacenar el número de orden del pedido, 
    #order_number es llamado nro_pedido donde el profe
    order_number = models.CharField(max_length=20, null=True)

    # Define un campo DecimalField para almacenar el precio total del pedido, con un máximo de 10 dígitos y 2 decimales
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # Define las opciones para el estado del pedido usando una tupla de tuplas (choices)
    STATUS_CHOICES = [
        ('0', 'Pending'),
        ('1', 'Paid'),
    ]

    # Define el campo para el estado del pedido y utiliza las opciones definidas anteriormente
    order_status = models.CharField(max_length=1, default='0', choices=STATUS_CHOICES)

    # Define el método __str__ para representar el objeto Pedido como una cadena
    #El método __str__ se utiliza para proporcionar una representación legible para humanos 
    def __str__(self):
        return f"Order number: {self.order_number}"



# Define el modelo PedidoDetalle para representar los detalles de un pedido
class PedidoDetalle(models.Model):

    # Define una relación ForeignKey con el modelo Pedido para representar el pedido al que pertenece este detalle
    pedido = models.ForeignKey(Pedido, on_delete=models.RESTRICT)

    # Define una relación ForeignKey con el modelo Producto para representar el producto que se incluye en este detalle
    product_name = models.ForeignKey(Producto, on_delete=models.RESTRICT)

    # Define un campo PositiveIntegerField para almacenar la cantidad de productos en este detalle
    quantity = models.PositiveIntegerField(default=1)

    # Almacena el costo que tuvo el producto en el momento de venderlo.
    # Es el precio del producto por la cantidad del mismo producto que se va a comprar
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)  # Añadí los argumentos max_digits y decimal_places

    # Define el método __str__ para representar el objeto PedidoDetalle como una cadena
    #El método __str__ se utiliza para proporcionar una representación legible para humanos 
    def __str__(self):
        # Retorna una cadena que incluye el nombre del producto y el nombre de usuario del cliente que hizo el pedido
        return f"Producto: {self.product_name.name} - Pedido de: {self.pedido.customer.usuario.username}"

pedidos/views.py
from django.shortcuts import redirect, render

#Los decoradores en Django, como @login_required, son funciones que modifican el comportamiento de otras funciones o métodos en Python
from django.contrib.auth.decorators import login_required

from autenticacion.forms import ClienteForm
from autenticacion.models import Cliente
from django.contrib.auth.models import User

from pedidos.models import Pedido, PedidoDetalle
from web.carrito import Cart
from web.models import Producto

from django.urls import reverse

from paypal.standard.forms import PayPalPaymentsForm
from django.core.mail import send_mail
# Create your views here.

@login_required
def registrarPedido(request):
    try:

        # Obtiene el cliente asociado al usuario actualmente autenticado o que inicio sesion
        clienteEditar = Cliente.objects.get(usuario=request.user)

        # Prepara los datos del cliente para prellenar el formulario
        datacliente = {
            'name': request.user.first_name,  # Nombre del usuario

            'Last_name': request.user.last_name,  # Apellido del usuario

            'email': request.user.email,  # Correo electrónico del usuario

            'address': clienteEditar.address,  # Dirección del cliente

            'phone_number': clienteEditar.phone_number,  # Número de teléfono del cliente

            'id_card': clienteEditar.id_card,  # Número de identificación del cliente

            'gender': clienteEditar.Gender,  # Género del cliente

            'birthdate': clienteEditar.birth_date,  # Fecha de nacimiento del cliente
        }

    #si el usuario no existe estrae solamente estos tres valores
    except:
        datacliente = {
            'name': request.user.first_name,  # Nombre del usuario

            'Last_name': request.user.last_name,  # Apellido del usuario

            'email': request.user.email, 
        }

    frmCliente=ClienteForm(datacliente)

    context={
        'frmCliente': frmCliente
    }

    return render(request, 'pedido.html', context)


@login_required
# Vista de confirmación de pedido
def confirmarPedido(request):

    context = {}

    if request.method == "POST":
        
        # Actualizamos datos del usuario, estos datos corresponden a la tabla usuario
        actUsuario = User.objects.get(pk=request.user.id)

        actUsuario.first_name = request.POST['name']

        actUsuario.last_name = request.POST['Last_name']
        """if 'last_name' in request.POST:
            last_name = request.POST['last_name']
        else:
            last_name = None  # o el valor por defecto que desees"""


        actUsuario.save()

        # Registramos o actualizamos cliente dependiento si  el cliente existe o no 
        try:
            
            #En esta linea de codigo se está tratando de obtener un objeto del modelo Cliente de la base de datos donde el campo usuario coincide con el usuario actualmente autenticado (request.user).
            clientePedido = Cliente.objects.get(usuario=request.user)
            clientePedido.phone_number = request.POST['phone_number']
            clientePedido.address = request.POST['address']
            clientePedido.save()

        # Si el cliente no existe, creamos un nuevo cliente
        except Cliente.DoesNotExist:
            clientePedido = Cliente()
            clientePedido.usuario = actUsuario
            clientePedido.address = request.POST['address']
            clientePedido.phone_number = request.POST['phone_number']
            clientePedido.save()

        # Registramos un nuevo pedido
        nroPedido = ''
        #el monto total esta almacenado en una variable de sesion llamada cartMontoTotal
        montoTotal = float(request.session.get('cartMontoTotal'))
        nuevoPedido = Pedido()
        nuevoPedido.customer = clientePedido
        nuevoPedido.save()

        #Registramos los detalles del pedido
        carritoPedido=request.session.get('cart')

        # Iteramos a través de los elementos del carrito de compras almacenados en la sesión del usuario
        for key, value in carritoPedido.items():

            # Obtenemos el producto correspondiente a partir de su ID almacenado en el carrito
            productoPedido = Producto.objects.get(pk=value['producto_id'])

            # Creamos una nueva instancia del modelo 'PedidoDetalle' para registrar los detalles del pedido
            detalle = PedidoDetalle()

            # Asignamos el pedido actual al detalle del pedido
            detalle.pedido = nuevoPedido

            # Al detalle del pedido asignamos el nombre del producto, este campo en nuestro modelo tiene una relacion ForeignKey con la tabla producto
            detalle.product_name = productoPedido

            # Asignamos la cantidad de productos del carrito al detalle del pedido
            detalle.cantidad = int(value['quantity'])

            # Asignamos el subtotal del producto al detalle del pedido
            detalle.subtotal = float(value['subtotal'])

            # Guardamos el detalle del pedido en la base de datos
            detalle.save()


        # Actualizar pedido
        #creamos un numero de pedido con la fecha de registro y pedido id con la palabra PED  de pedido
        #strftime('%Y')  convierta la fecha a una variable string
        nroPedido = 'PED' + nuevoPedido.registration_date.strftime('%Y') + str(nuevoPedido.id)
        nuevoPedido.order_number = nroPedido
        nuevoPedido.total_price = montoTotal
        nuevoPedido.save()

        #REGISTRAR VARIABLE DE SESSION PARA EL PEDIDO
           #Creamos nueva variable de session 
        request.session['pedidoId'] = nuevoPedido.id

        #CREAMOS BOTON DE PAYPAL
            # What you want the button to do.        
        paypal_dict = {
            "business": "sb-mtg9m27653910@business.example.com",
            "amount": montoTotal,
            "item_name": "CODIGO DEL PEDIDO: " + nroPedido,
            "invoice": nroPedido,
            "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
            "return": request.build_absolute_uri(reverse('pedido:gracias')),
            "cancel_return": request.build_absolute_uri(reverse('autenticacion:logoutUsuario')),
            "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
        }

        # Create the instance.
        form = PayPalPaymentsForm(initial=paypal_dict)
        


        context={
            #nuevoPedido es una instancia de la clase pedido
            'pedido':nuevoPedido,
            "form": form,
        }


        #limpiamos el carrito de compras
        carrito=Cart(request)
        carrito.clear()

    # Renderizamos el template 'compra.html' como respuesta
    return render(request, 'compra.html', context)


#vista para mostrar gracias despues que el usuario ha hecho la compra
def gracias(request):
    #cuando retornamos al gracias despues de hacer la compra en nuestra url, se nos retorna una variable llmada PayerID
    #En el contexto de PayPal y otras pasarelas de pago, PayerID se refiere al identificador único del pagador (o comprador) durante una transacción. Es un identificador único asociado a la cuenta o método de pago del usuario que realizó la compra. Cuando un usuario completa un proceso de pago en PayPal y es redirigido de vuelta a tu sitio web, el PayerID se utiliza para identificar de manera única al comprador y asociar la transacción a su cuenta de PayPal. Este identificador puede ser utilizado para realizar operaciones posteriores, como reembolsos o consultas de estado de pago.
    paypalId = request.GET.get('PayerID', None)#PayerID Es el nombre de la variable, si no la encuentra le ponemos None

    if paypalId is not None:

        #pedidoId es una variable de sesionn y con la sgt line ade codigo obtenemos su valor 
        pedidoId = request.session.get('pedidoId')

        #obtenemos el pedido asignado a la variable id
        pedido = Pedido.objects.get(pk=pedidoId)

        #1 significa pagado, lo asignamos en nuestro modelo pedido
        pedido.order_status = '1'

        #guardamos cambius
        pedido.save()

        #enviamos correo de confirmacion al usuario con los detalles de su pedido
        send_mail(
            #subject del mail
            'THANK YOU FOR YOUR PURCHASE',

            #Our message
            'your order number is ' + pedido.order_number,

            #donde enviamos nuestro mail
            'ricardoantoniogomezvillalobos@gmail.com',

            #correo del usuario o lista de correos
            [request.user.email ],

            fail_silently=False,

            
        )
        #print(pedido.order_number)  prueba si se envia el order number correctamente
        context = {
            #en nuestra pagina de gracias queremos poner la informacion del pedido e informar al usuario que le enviaremos un correo con la info del pedidu
            'pedido':pedido
        }
    else:
        return redirect('/')

    return render(request, 'gracias.html', context)






"""PRUEBA DE LA LIBRERIA PAYPAL"""


def view_that_asks_for_money(request):

    # What you want the button to do.
    paypal_dict = {
        "business": "sb-mtg9m27653910@business.example.com",
        "amount": "10.00",
        "item_name": "name of the item",
        "invoice": "unique-invoice-id",
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('web:index')),
        "cancel_return": request.build_absolute_uri(reverse('autenticacion:logoutUsuario')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form}
    return render(request, "payment.html", context)

web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Cart</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="product.html" class="prod-li-img">
                    <img src="{{ value.image }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{value.category}}</a>
                        </p>
                        <h3><a href="product.html">{{ value.name }}</a></h3>
                    </div><!--
    No Space
    --><div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Price</p>
                        <p class="prod-li-price">${{value.price}}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                             <!-- <input type="text" value="{{value.quantity}}"> -->
                             <input type="text" name="quantity" value="{{value.quantity}}">

                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>

                        
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{value.subtotal}}</p>
                    </div>
                </div><!--
No Space
--></div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id%}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Remove</span></a>
                    </p>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Marca:</dt>
                    <dd><a href="#">{{value.marca}}</a></dd>
                    <dt>Peso:</dt>
                    <dd>{{value.peso}} kg</dd>
                    <dt>Dimensiones:</dt>
                    <dd>{{value.dimension}}</dd>
                    <dt>Сolor:</dt>
                    <dd>{{value.color}}</dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Clean cart</a>
            <a href="{%url 'pedido:registrarPedido'%}" class="checkout-button button">Make an order</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <!-- llamamos a la variable de sesion que definimos en carrito.py llamada cartMontoTotal-->
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

web/templates/compra.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.order_number}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">

            <h2>Fecha : {{pedido.registration_date}}</h2>
            <!-- consulta inversa que se utiliza para obtener todos los objetos de la clase PedidoDetalle relacionados con un objeto específico de la clase Pedido. -->
            <!-- detalle representa cada objeto individual de la clase PedidoDetalle relacionado con el objeto pedido -->
           {%for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{detalle.product_name.image.url}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.product_name.category}}</a>
                            </p>
                            <h3><a href="product.html">{{detalle.product_name.name}}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.product_name.price}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.quantity}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
           {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                <!-- El método render en Django se utiliza para convertir un formulario de Django en su representación HTML.  -->
                <!-- {{ formPaypal.render }} en tu plantilla se traduce a todo el código HTML necesario para mostrar el formulario formPaypal. Esto incluirá las etiquetas <form>, los campos de entrada (<input>), las áreas de texto (<textarea>), los botones y cualquier otra cosa necesaria para que el formulario funcione correctamente en una página web. -->
                {{form.render}}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.total_price}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/cuenta.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{ user.username }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'autenticacion:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{ frmCliente|crispy }}
                        <p class="auth-submit">
                            <input type="submit" value="Update Data">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>                                                <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Login</h2>
                <form method="post" class="login" action="{% url 'autenticacion:loginUsuario' %}">
                    {% csrf_token %}
                    <!-- este input hidden es para pasar la pagina de destino almacenada en destino en la vista loginUsuario por el metodo post -->
                    <input type="hidden" name="destino" value="{{destino}}">
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger"> {{mensajeError}}</label>
                    </p>
                    <p class="auth-lost_password">
                        <a href="#">Lost your password?</a>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Registration</h2>
                <form method="post" class="register" action="{% url 'autenticacion:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <!-- la info que ingresa el user se guarda en nuevo usuario -->
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <!-- la infor que ingresa el user se guarda en nuevopasword -->
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Sign up">
                    </p>
                </form>
            </div>
        </div>


    </div>
</article>

{% endblock %}

web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">ORDER REGISTRATION</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>pedido</li>
    </ul>
    <form method="post" action="{% url 'pedido:confirmarPedido' %}" class="register">
    {% csrf_token %}
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Personal Information</h2>
                    <p>
                        <label for="username">Name<span class="required">*</span></label>
                        {{frmCliente.name}}
                    </p>
                    <p>
                        <label for="username">Last Name<span class="required">*</span></label>
                        {{frmCliente.Last_name}}
                    </p>
                </div>
                <div class="auth-col">
                    <h2>Shipping Information</h2>
                    <p>
                        <label for="username">Telephone<span class="required">*</span></label>
                        {{frmCliente.phone_number}}
                    </p>
                    <p>
                        <label for="username">address<span class="required">*</span></label>
                        {{frmCliente.address}}
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <h2>Product Confirmation</h2>
            <div class="woocommerce prod-litems section-list">
                {% for key,value in request.session.cart.items %}
                <article class="prod-li sectls">
                    <div class="prod-li-inner">
                        <a href="#" class="prod-li-img">
                            <img src="{{ value.image }}" alt="">
                        </a>
                        <div class="prod-li-cont">
                            <div class="prod-li-ttl-wrap">
                                <p>
                                    <a href="#">value.category</a>
                                </p>
                                <h3><a href="product.html">{{ value.name }}</a></h3>
                            </div>
                            <div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{value.price}}</p>
                                </div>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{value.quantity}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.subtotal}}</p>
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}
        </div>
        <div class="cart-actions">
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
                    </div>
                </div>
        </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <p class="auth-submit">
                        <input type="submit" value="Confirm Order">
                    </p>
            </div>
        </div>
    </article>
    </form>
{% endblock %}