shop/urls.py
from django.contrib import admin
from django.urls import path, include

# Importa la configuración global de tu proyecto Django
from django.conf import settings

# Importa la función 'static' para servir archivos estáticos como imágenes y hojas de estilo CSS, para que puedas ver cómo se ven en tu aplicación.
from django.conf.urls.static import static

# Define las URL de tu aplicación
urlpatterns = [
    path('admin/', admin.site.urls),
    #Dejo la raiz vacia para definir que ese sea su pag home

    path('', include('web.urls')),

    path('autenticacion/', include('autenticacion.urls')),
    
    path('pedidos/', include('pedidos.urls')),

    path('paypal/', include("paypal.standard.ipn.urls")),
]

# Si el modo DEBUG está activado (entorno de desarrollo), 
# agrega las URL para servir archivos multimedia (MEDIA_URL)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

from . import views


app_name='web'
# Define las URL de tu aplicación
urlpatterns = [
    #dejo la raiz vacia para definir que ese sera su pagina home
    path('', views.index, name='index'),
    path('ProductosPorCategoria/<int:categoria_id>', views.ProductosPorCategoria, name='ProductosPorCategoria'),
    path('BuscarProducto', views.BuscarProducto, name='BuscarProducto'),
    path('Producto/<int:producto_id>', views.ProductoDetalle, name='ProductoDetalle'),
    path('carrito', views.carrito, name='carrito'),
    path('agregarCarrito/<int:producto_id>', views.agregarCarrito, name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>', views.eliminarProductoCarrito, name='eliminarProductoCarrito'),
    path('limpiarCarrito', views.limpiarCarrito, name='limpiarCarrito'),
]

web/templates/includes/catalogo/catalogo.html
<!-- Contenedor principal para mostrar productos -->
<div class="row prod-items prod-items-2">
    <!-- Comienza un bucle para recorrer cada producto en la variable "productos" -->
    {% for producto in productos %}
    <!-- Cada producto se muestra en un artículo -->
    <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <!-- Contenedor de información del producto -->
        <div class="sectgl prod-i">
            <!-- Parte superior del producto -->
            <div class="prod-i-top">
                <!-- Enlace de la imagen del producto -->
                <a class="prod-i-img" href="{% url 'web:ProductoDetalle' producto.id %}">
                    
                    {% if producto.image %}
                    <!-- Mostrar la imagen del producto utilizando la URL almacenada en "producto.image.url" -->
                    <img src="{{producto.image.url}}" alt="">

                    {% else %}
                    <!-- si no existe la imagen, ponemos una imagen por defecto -->
                    <img src="https://via.placeholder.com/150" alt="">
                    {% endif %}
                </a>
                <!-- Acciones disponibles para el producto, como agregar al carrito -->
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <!-- Botón para agregar el producto al carrito -->
                        <p class="prod-i-cart">
                            <a href="{% url 'web:agregarCarrito' producto.id %}" class="hover-label prod-addbtn">
                                <!-- Ícono de carrito de compra -->
                                <i class="icon ion-android-cart"></i>
                                <!-- Texto "Añadir al carrito" -->
                                <span>add to cart</span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <!-- Parte inferior del producto con detalles e información -->
            <div class="prod-i-bot">
                <!-- Información sobre el precio del producto -->
                <div class="prod-i-info">
                    <p class="prod-i-price">${{producto.price}}</p>
                    <!-- Categoría del producto con enlace -->
                    <p class="prod-i-categ"><a href="#">{{producto.category}}</a></p>
                </div>
                <!-- Título del producto con enlace -->
                <h3 class="prod-i-ttl"><a href="{% url 'web:ProductoDetalle' producto.id %}">{{producto.name}}</a></h3>
            </div>
        </div>
    </article>
    <!-- Finaliza el bucle -->
    {% endfor %}
</div>

web/templates/includes/catalogo/categorias.html
<div class="blog-sb-widget multishopcategories_widget">

    <!-- Título del widget de categorías -->
    <h3 class="widgettitle">Categories</h3>

    <div class="section-sb-current">
        <!-- Lista de categorías -->
        <ul class="section-sb-list">

            <!-- Comienza un bucle para recorrer cada categoría en la variable "categorias" -->
            {% for categoria in categorias %}

            <li>
                <!-- Enlace de la categoría, se le pasa al enlace el id para esccger una categoria en especifico -->
                <a href="{% url 'web:ProductosPorCategoria' categoria.id %}">

                    <!-- Nombre de la categoría -->
                    <span class="section-sb-label">{{categoria.name}}
                        <!-- Contador: muestra la cantidad de productos en esta categoría -->
                        <!-- Utiliza "categoria.producto_set.all.count" para contar todos los productos relacionados con esta categoría -->
                        <!-- "categoria.producto_set.all" representa todos los productos asociados a esta categoría -->
                        <!-- "count" cuenta la cantidad de productos -->
                        <span class="count">{{categoria.producto_set.all.count}}</span>
                    </span>
                </a>
            </li>

            <!-- Finaliza el bucle -->
            {% endfor %}
        </ul>
    </div>
</div>